- NumPy ndarrays can contain only one datatype. --> print(nparrays.dtype)
- NaN is an acronym for Not a Number
- #### print(np.array([2,4,6,8]) < 5)

In [7]:
# create csf with sample data
# randomly insert 100 to the data and randomly insert 100 values to the second column

import numpy as np
import random
import csv

comumn_names = 'ABCDEF'
columns = [x for x in comumn_names]

columns_no, rows_no = len(columns), 10
                      
gen_data_list = [[random.randint(0,100) for column in range(0,columns_no) ] for row in range(0, rows_no)]

# randomly insert 100 to the data and randomly insert 100 values to the second column
quantity = random.randint(1,rows_no - 1)
for i in range(quantity):
    rand_column = random.randint(0,columns_no - 1)
    rand_row = random.randint(0,rows_no - 1)
    gen_data_list[rand_row][rand_column] = 100
    gen_data_list[rand_row][1] = 100
    

with open('test.csv', 'w+',newline='') as f:
    writer = csv.writer(f)
    writer.writerow(columns) # frite column names
    writer.writerows(gen_data_list) # write multiple rows
    



In [8]:
# reading CSV with numpy
data = np.genfromtxt('test.csv', delimiter=',')
print(data.shape)
data

(11, 6)


array([[ nan,  nan,  nan,  nan,  nan,  nan],
       [ 36., 100., 100.,  63.,  43.,  86.],
       [ 49.,  42.,  49.,  23.,   5.,  17.],
       [100., 100.,  18.,  12.,  59., 100.],
       [ 79.,  20.,   6.,  88.,  23.,  32.],
       [  5., 100.,  39.,  60.,  51., 100.],
       [ 14.,  32.,  27.,  28.,  25.,   7.],
       [ 71.,  83.,  27.,  42.,  60.,   6.],
       [ 41., 100.,  42.,  38.,  43., 100.],
       [ 14., 100., 100.,  76.,  57.,  76.],
       [ 45., 100.,  82.,  24.,  86.,  15.]])

NaN is an acronym for Not a Number

In [9]:
# removing header from nparray
data = data[1:,:]

print(data.shape)
data

(10, 6)


array([[ 36., 100., 100.,  63.,  43.,  86.],
       [ 49.,  42.,  49.,  23.,   5.,  17.],
       [100., 100.,  18.,  12.,  59., 100.],
       [ 79.,  20.,   6.,  88.,  23.,  32.],
       [  5., 100.,  39.,  60.,  51., 100.],
       [ 14.,  32.,  27.,  28.,  25.,   7.],
       [ 71.,  83.,  27.,  42.,  60.,   6.],
       [ 41., 100.,  42.,  38.,  43., 100.],
       [ 14., 100., 100.,  76.,  57.,  76.],
       [ 45., 100.,  82.,  24.,  86.,  15.]])

In [10]:
print(np.array([2,4,6,8]) + 10) # + 10 operation applies to each value in the array

[12 14 16 18]


In [11]:
print(np.array([2,4,6,8]) < 5)

[ True  True False False]


In [12]:
# check witch random values in the CSV created randomely are less than 50
print(data <50)

[[ True False False False  True False]
 [ True  True  True  True  True  True]
 [False False  True  True False False]
 [False  True  True False  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False  True  True False  True]
 [ True False  True  True  True False]
 [ True False False False False False]
 [ True False False  True False  True]]


In [13]:

'''
Call numpy.sum(a) to get the sum of the array a. The result will be 
NaN if and only if a has one or more NaN values. Call numpy.isnan(x) to check if the previous result x is NaN.

array_sum = np.sum(dataset_numpy)
array_has_nan = np.isnan(array_sum)
print(array_has_nan)


'''

'\nCall numpy.sum(a) to get the sum of the array a. The result will be \nNaN if and only if a has one or more NaN values. Call numpy.isnan(x) to check if the previous result x is NaN.\n\narray_sum = np.sum(dataset_numpy)\narray_has_nan = np.isnan(array_sum)\nprint(array_has_nan)\n\n\n'

In [41]:

nparray = np.array([[ 36., 10., 20.,  10.,  60.,  0.],
               [0., 0.,   0.,  48.,  0.,  0.],
              [100., 80.,   0.,  0.,  20,  0.],
             ])

nparray.shape

dropoff_newark_bool = nparray[:, 1:].sum(axis=1) == 100
newark_count = nparray[dropoff_newark_bool]

newark_count

array([[ 36.,  10.,  20.,  10.,  60.,   0.],
       [100.,  80.,   0.,   0.,  20.,   0.]])