In [1]:
import numpy as np

In [2]:
# arrays
tablica = np.array([1,2,3,4,5,6,7,8,9])
tablica

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# tablica zerowymiarowa
tablica0D = np.array(2)
tablica0D

array(2)

In [4]:
# check dimensions
print(tablica0D.ndim)
print(tablica.ndim)

0
1


In [5]:
# creating 2d array 
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [6]:
# 2d array
tablica2d = np.array([[1,2,3], [4,5,6]])
print(tablica2d.ndim)
tablica2d

2


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 2d - would work in python but in numpy not
tablica2d = np.array([[1,2,3], [4,3]])
print(tablica2d.ndim)
tablica2d

1


C:\Users\Ukasz\Anaconda3\envs\geopandas\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


array([list([1, 2, 3]), list([4, 3])], dtype=object)

In [8]:
# tablica tylko z 0
tablica = np.ones(8)
tablica

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# range in numpy
t = np.arange(5)
t

array([0, 1, 2, 3, 4])

In [10]:
# range in numpy
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# linespace = rozklad -  rozklada po rowno wartosci w przedziale 5 na 100 elementow
tablica = np.linspace(0, 100, num=5)
tablica

array([  0.,  25.,  50.,  75., 100.])

In [13]:
tablica = np.array([1,2,3,4,5,6,7,8,9])
tablica[0]

1

In [14]:
# 2d array
tablica2d = np.array([[1,2,3], [4,5,6]])
print(tablica2d[0])
tablica2d[0][0]

[1 2 3]


1

#### slicing

In [15]:
# slicing
tablica[:2]

array([1, 2])

In [16]:
# slicing from to every 2
tablica[0:8:2]

array([1, 3, 5, 7])

In [17]:
# slicing from to every 2
tablica[::2]

array([1, 3, 5, 7, 9])

In [18]:
tablica[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [19]:
list(tablica)[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [20]:
tablica2d = np.array([[1,2,3,11,22,33], [4,5,6,44,55,66]])
print(tablica2d[1,:2])
print(tablica2d[:,2])  # z obu wymiarow wez element o indeksie 2
print(tablica2d[0:2,0:2])  # wytnj lewy gorny rog 2 x 2

[4 5]
[3 6]
[[1 2]
 [4 5]]


types

In [21]:
# i - int, b - bool, f - float, M - datetime, 
# O - object, S - string
# U - unicode String

In [22]:
tablica = np.array(['bmw', 'audi', 'mercedes'])
tablica.dtype # checks dtype

dtype('<U8')

In [23]:
# <U8   - means - unicode less than 8 bites

In [24]:
# https://www.fileformat.info/info/charset/UTF-32/list.htm?start=3072
val = 255
for i in range(val):
    print(i, chr(i))


0 
1 
2 
3 
4 
5 
6 
7 
8
9 	
10 

11 
12 
13 
14 
15 
16 
17 
18 
19 
20 
21 
22 
23 
24 
25 
26 
27 
28 
29 
30 
31 
32  
33 !
34 "
35 #
36 $
37 %
38 &
39 '
40 (
41 )
42 *
43 +
44 ,
45 -
46 .
47 /
48 0
49 1
50 2
51 3
52 4
53 5
54 6
55 7
56 8
57 9
58 :
59 ;
60 <
61 =
62 >
63 ?
64 @
65 A
66 B
67 C
68 D
69 E
70 F
71 G
72 H
73 I
74 J
75 K
76 L
77 M
78 N
79 O
80 P
81 Q
82 R
83 S
84 T
85 U
86 V
87 W
88 X
89 Y
90 Z
91 [
92 \
93 ]
94 ^
95 _
96 `
97 a
98 b
99 c
100 d
101 e
102 f
103 g
104 h
105 i
106 j
107 k
108 l
109 m
110 n
111 o
112 p
113 q
114 r
115 s
116 t
117 u
118 v
119 w
120 x
121 y
122 z
123 {
124 |
125 }
126 ~
127 
128 €
129 
130 ‚
131 ƒ
132 „
133 …
134 †
135 ‡
136 ˆ
137 ‰
138 Š
139 ‹
140 Œ
141 
142 Ž
143 
144 
145 ‘
146 ’
147 “
148 ”
149 •
150 –
151 —
152 ˜
153 ™
154 š
155 ›
156 œ
157 
158 ž
159 Ÿ
160  
161 ¡
162 ¢
163 £
164 ¤
165 ¥
166 ¦
167 §
168 ¨
169 ©
170 ª
171 «
172 ¬
173 ­
174 ®
175 ¯
176 °
177 ±
178 ²
179 ³
180 ´
181 µ
182 ¶
183 ·
184 ¸
185

In [25]:
var = 225
print(chr(var))
var2 = 'ß'
print(ord(var2))


á
223


In [26]:
tablica = np.array([1,2,3,4,5,6,7], dtype='U')
print(tablica)
print(tablica.dtype)

['1' '2' '3' '4' '5' '6' '7']
<U1


In [27]:
arr = np.array([5.122,5.7899,6.788])
arr = arr.astype('i')
print(arr, arr.dtype)

[5 5 6] int32


In [28]:
# boolean will check for us 
arr = arr.astype('bool')
print(arr, arr.dtype)

[ True  True  True] bool


#### copy and view

In [29]:
tablica = np.array([1,2,3,4,5,6,7])
kopia = tablica

tablica[1] = 100

print(tablica)
print(kopia)

[  1 100   3   4   5   6   7]
[  1 100   3   4   5   6   7]


In [30]:
tablica = np.array([1,2,3,4,5,6,7])
kopia = tablica.copy() # kopia zawartosci do nowej pamieci

tablica[1] = 100

print(tablica)
print(kopia)

[  1 100   3   4   5   6   7]
[1 2 3 4 5 6 7]


In [31]:
tablica = np.array([1,2,3,4,5,6,7])
kopia = tablica.view()  # kopia referencji do orginalu

tablica[1] = 100

print(tablica)
print(kopia)

[  1 100   3   4   5   6   7]
[  1 100   3   4   5   6   7]


#### shape

In [32]:
tablica2d = np.array([[1,2,3,11,22,33], [4,5,6,44,55,66]])
tablica2d.shape  # returns 2 columns and 6 elements

(2, 6)

In [33]:
# 1d to 3d array
tablica = np.array([1,2,3,4,5,6,7,8])
tablica.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
for i in tablica.reshape(2,4):
    print (i)

[1 2 3 4]
[5 6 7 8]


In [35]:
tablica2d = np.array([[1,2,3,11,22,33], [4,5,6,44,55,66]])

# goes through every element in each nested array
# dowolna plaszczyzna
for e in np.nditer(tablica2d):
    print(e)

1
2
3
11
22
33
4
5
6
44
55
66


In [36]:
tablica2d = np.array([[1,2,3,11,22,33], [4,5,6,44,55,66]])

for nr, e in np.ndenumerate(tablica2d):
    print(nr, e)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 11
(0, 4) 22
(0, 5) 33
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 44
(1, 4) 55
(1, 5) 66


In [37]:
t1 = np.array([1,2,9])
t2 = np.array([8,7,6])

tablica = np.concatenate((t1, t2))
tablica

array([1, 2, 9, 8, 7, 6])

In [38]:
t1 = np.array([[1,2], [3,4]])
t2 = np.array([[5,6], [7,8]])

# os pozioma (row) to 0, os pionowa to 1 (column)
tablica = np.concatenate((t1, t2), axis=1)
print(tablica.shape)
tablica

(2, 4)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
t1 = np.array([[1,2], [3,4]])
t2 = np.array([[5,6], [7,8]])

# os pozioma (row) to 0, os pionowa to 1 (column)
tablica = np.concatenate((t1, t2), axis=0)
print(tablica.shape)
tablica

(4, 2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### nalozenia

In [40]:
t1 = np.array([1,2,9])
t2 = np.array([8,7,6])

tablica = np.stack((t1,t2), axis=0) # rows
print(tablica.ndim)
tablica

2


array([[1, 2, 9],
       [8, 7, 6]])

In [41]:
t1 = np.array([1,2,9])
t2 = np.array([8,7,6])

tablica = np.stack((t1,t2), axis=1) # columns
print(tablica.ndim)
tablica

2


array([[1, 8],
       [2, 7],
       [9, 6]])

In [42]:
t1 = np.array([1,2,9])
t2 = np.array([8,7,6])

tablica = np.hstack((t1,t2)) # row
print(tablica.ndim)
tablica

1


array([1, 2, 9, 8, 7, 6])

In [43]:
t1 = np.array([1,2,9])
t2 = np.array([8,7,6])

tablica = np.vstack((t1,t2)) # columns
print(tablica.ndim)
tablica

2


array([[1, 2, 9],
       [8, 7, 6]])

In [44]:
t1 = np.array([1,2,9,3,4,5,6])
np.array_split(t1,3)

[array([1, 2, 9]), array([3, 4]), array([5, 6])]

#### WHERE

In [45]:
t1 = np.array([1,2,9,3,4,5,2])
np.where(t1 == 2)  # returns indexes

(array([1, 6], dtype=int64),)

In [46]:
# 2d array
tablica2d = np.array([[1,2,3], [4,2,6]])
np.where(tablica2d == 2)  # returns indexes

(array([0, 1], dtype=int64), array([1, 1], dtype=int64))

In [47]:
tablica2d[0, 1]

2

In [48]:
tablica2d[1, 1]

2

In [49]:
ind = np.where(tablica2d == 2)  # returns indexes
type(ind)

tuple

In [50]:
ind[0]

array([0, 1], dtype=int64)

#### sort

In [51]:
tablica2d = np.array([[33,5,88], [66,72,16]])
np.sort(tablica2d)

array([[ 5, 33, 88],
       [16, 66, 72]])

#### filtr

In [52]:
filtr = [True, False, True, False, False, True]
tablica = np.array([1,2,3,4,5,6])
print(tablica[filtr])

[1 3 6]


In [53]:
# filtr only even
filtr = tablica % 2 == 0
print(tablica[filtr])

[2 4 6]


In [54]:
tablica2d = np.array([[33,5,88], [66,33,16]])
filtr = tablica2d > 50
print(tablica2d[filtr])

[88 66]


In [55]:
tablica2d = np.array([[33,5,88], [66,33,16]])
tablica2d[tablica2d == 33] = 0
tablica2d

array([[ 0,  5, 88],
       [66,  0, 16]])

In [56]:
'''
Zadania 1 Wylosuj tablice 10 x 10 z wartosciami od -10 do 10
Zadanie 2 Wskaz wartosc najczesciej wystepujaca z zadania pierwszego
'''

'\nZadania 1 Wylosuj tablice 10 x 10 z wartosciami od -10 do 10\nZadanie 2 Wskaz wartosc najczesciej wystepujaca z zadania pierwszego\n'

In [57]:
# solution 1
tablica = np.random.randint(-10,10,size=(10, 10))
print(tablica)
unique, counts = np.unique(tablica, return_inverse=True)
print(unique[np.argmax(np.bincount(counts))])

u = {int(x):0 for x in list(unique)}
for e in np.nditer(tablica):
    u[int(e)] = u[int(e)] + 1

u = dict(sorted(u.items(), key=lambda item: item[1], reverse=True))
print(u)
maxi = max(list(u.values()))
new_dict = {value:key for (key,value) in u.items()}
new_dict[maxi]

[[  5   4  -5   9   7  -8  -2  -9 -10  -2]
 [ -3   5   9   3  -8  -2   7  -4   8 -10]
 [  9   2   6   7   5  -9  -6  -4  -2  -9]
 [ -9   1  -3   1   7  -3   4  -3  -7   2]
 [ -6  -3 -10  -1  -6   3  -3   8   2   7]
 [ -8   8   8  -9  -9   4   7  -7   7   1]
 [  0  -2  -4  -9  -7  -6  -5  -3  -6  -7]
 [ -2  -3  -4  -9  -8  -1   2  -4 -10  -8]
 [  9   2   6 -10   5  -8   7   9  -8  -7]
 [ -9   6  -1   9  -8   9   1   1  -7  -1]]
-9
{-9: 9, -8: 8, -3: 8, 7: 8, 9: 7, -7: 6, -2: 6, -10: 5, -6: 5, -4: 5, 1: 5, 2: 5, -1: 4, 5: 4, 8: 4, 4: 3, 6: 3, -5: 2, 3: 2, 0: 1}


-9

In [58]:
# solution 2
# reshape 2d to on 1d 
tablica = tablica.reshape(-1)
print(np.bincount(tablica + 10).argmax()-10)


-9


In [59]:
'''
zad 3 posortuj tablice zad 1 w wierszach a potem w kolumnach
'''

'\nzad 3 posortuj tablice zad 1 w wierszach a potem w kolumnach\n'

In [60]:
# solution 1
tablica = np.random.randint(-10,10,size=(10, 10))
print(tablica)
tablica = np.sort(tablica)
print(tablica)
tablica = tablica[tablica[:, 0].argsort()]
print(tablica)

[[ -5   5   1  -7  -8   8   1   8   5  -6]
 [ -4  -9  -1   1  -1  -3   4  -6  -1  -7]
 [ -4  -9   1   8   3  -2  -1 -10   9   5]
 [ -5  -3   7   4   1 -10  -6   3 -10   4]
 [  9   5   8   8   1  -8  -6  -5 -10   6]
 [ -7   3  -8  -6   2   2   2   5  -2  -2]
 [-10  -2  -9   2   8  -2  -7  -9   4 -10]
 [ -6   1  -6  -3   5  -9  -6   5   4   1]
 [  5   8   4  -2   3  -9 -10  -5   2  -4]
 [  3  -5  -9   3   5  -4  -3   4  -9  -7]]
[[ -8  -7  -6  -5   1   1   5   5   8   8]
 [ -9  -7  -6  -4  -3  -1  -1  -1   1   4]
 [-10  -9  -4  -2  -1   1   3   5   8   9]
 [-10 -10  -6  -5  -3   1   3   4   4   7]
 [-10  -8  -6  -5   1   5   6   8   8   9]
 [ -8  -7  -6  -2  -2   2   2   2   3   5]
 [-10 -10  -9  -9  -7  -2  -2   2   4   8]
 [ -9  -6  -6  -6  -3   1   1   4   5   5]
 [-10  -9  -5  -4  -2   2   3   4   5   8]
 [ -9  -9  -7  -5  -4  -3   3   3   4   5]]
[[-10  -9  -4  -2  -1   1   3   5   8   9]
 [-10 -10  -6  -5  -3   1   3   4   4   7]
 [-10  -8  -6  -5   1   5   6   8   8   9]
 [-10 -10

In [61]:
# solution 2
tablica = np.random.randint(-10,10,size=(10, 10))
print(tablica)
tablica = np.sort(tablica)
print(tablica)
index = np.argsort(tablica, axis=0)
tablica = np.take_along_axis(tablica, index, axis=0)
print(tablica)

[[  2   6   7 -10   1   1   9   3  -9  -2]
 [  9  -9   5  -6  -2  -3   4   7   7   3]
 [  6   3  -7   0   9  -4   6 -10  -1   2]
 [ -3  -9  -3   4  -2   2   5   8   0 -10]
 [  1   3   0   8  -3   1  -2   9  -5   1]
 [  5   8   3  -1 -10   3  -2   2   2  -8]
 [  4   8  -9 -10   0   7  -1   8  -4   9]
 [ -8  -9  -9   2   7   5   5 -10  -7   8]
 [  0  -2   0   9 -10   0  -5  -2   8   9]
 [ -6  -8   0   2   9   6  -3 -10   2  -7]]
[[-10  -9  -2   1   1   2   3   6   7   9]
 [ -9  -6  -3  -2   3   4   5   7   7   9]
 [-10  -7  -4  -1   0   2   3   6   6   9]
 [-10  -9  -3  -3  -2   0   2   4   5   8]
 [ -5  -3  -2   0   1   1   1   3   8   9]
 [-10  -8  -2  -1   2   2   3   3   5   8]
 [-10  -9  -4  -1   0   4   7   8   8   9]
 [-10  -9  -9  -8  -7   2   5   5   7   8]
 [-10  -5  -2  -2   0   0   0   8   9   9]
 [-10  -8  -7  -6  -3   0   2   2   6   9]]
[[-10  -9  -9  -8  -7   0   0   2   5   8]
 [-10  -9  -7  -6  -3   0   1   3   5   8]
 [-10  -9  -4  -3  -2   0   2   3   6   8]
 [-10  -9

In [62]:
# solution 3
tablica = np.random.randint(-10,10,size=(10, 10))
print(tablica)
tablica = np.sort(tablica)
print(tablica)
tablica = np.sort(tablica,axis=0)
print(tablica)

[[  2   3  -3  -6   3   8   9   1   1  -8]
 [ -2   4  -5   6   9   4  -6  -2  -5   0]
 [ -3 -10  -5   3  -9  -9  -2   8  -5   1]
 [ -5  -5   3   6 -10   5  -3   7  -8   5]
 [  5   4 -10  -5   8  -4  -3   7   5   1]
 [-10  -8   2   2   2  -3   8   7  -1  -5]
 [  5  -4  -7 -10   6  -5  -5  -8   0   0]
 [ -6   4   6   7  -1   5   5  -6   1  -1]
 [  5  -2   3   2   4   4  -2  -9   1  -5]
 [  6   4   5   7  -1 -10  -2   7  -4   7]]
[[ -8  -6  -3   1   1   2   3   3   8   9]
 [ -6  -5  -5  -2  -2   0   4   4   6   9]
 [-10  -9  -9  -5  -5  -3  -2   1   3   8]
 [-10  -8  -5  -5  -3   3   5   5   6   7]
 [-10  -5  -4  -3   1   4   5   5   7   8]
 [-10  -8  -5  -3  -1   2   2   2   7   8]
 [-10  -8  -7  -5  -5  -4   0   0   5   6]
 [ -6  -6  -1  -1   1   4   5   5   6   7]
 [ -9  -5  -2  -2   1   2   3   4   4   5]
 [-10  -4  -2  -1   4   5   6   7   7   7]]
[[-10  -9  -9  -5  -5  -4  -2   0   3   5]
 [-10  -8  -7  -5  -5  -3   0   1   4   6]
 [-10  -8  -5  -5  -3   0   2   2   5   7]
 [-10  -8

In [63]:
# wskaz w ktorym wierszu suma elementow jest najwieksza
tablica2d = np.array([[1,2,3], [4,5,6]])
print(tablica2d)
np.sum(tablica2d,axis=1)

[[1 2 3]
 [4 5 6]]


array([ 6, 15])

In [64]:
tablica = np.random.randint(-10,10,size=(10, 10))
print(tablica)
sumy = np.sum(tablica, axis=1)
sumy_lista = list(sumy)
print(sumy_lista)
index_max = np.argmax(sumy_lista)
print(index_max)

[[  8  -7   4   8  -8   6  -1  -7   1  -7]
 [ -1  -7  -2   7   8  -8   6  -2   0   1]
 [  4 -10   1   9   1   6   7  -4  -6  -8]
 [ -8   2 -10   9  -2  -7   0   1  -3   1]
 [ -6  -9   2   6  -1  -6   7  -4 -10  -2]
 [  5   5   0  -9   5   7   3  -7   3   5]
 [ -7   9  -9   5   3  -7  -3   7  -2   9]
 [  8   0   1  -7   2  -9   9   7  -6   7]
 [ -9   8   2   9  -8  -1   5  -2   8   7]
 [  9   1   4   3   4  -8  -8   4   6   6]]
[-3, 2, 0, -17, -23, 17, 5, 12, 19, 21]
9


In [65]:
np.sum(tablica, axis=1).argmax()

9

In [66]:
# wskaz w ktorej kolumnie suma elementow jest najwieksza
np.sum(tablica, axis=0).argmax()

3

In [67]:
# zad 5 tablica z 30 3l3m3ntow z wartosciami parzystymi od -50 d0 50

In [68]:
import random
arr = np.array([random.randrange(-50, 50, 2) for x in range(30)])
arr

array([ -6, -14,  20,  14, -42,  20,  10, -48, -32, -34, -48,  38,  20,
       -10,  12,  32, -50,  16, -18,  28,  32,  20, -14,  -4, -32,  32,
       -34,  20,  10, -22])

In [69]:
tablica = np.random.randint(-25,25,30) * 2
tablica

array([ 48, -34, -28, -48, -40, -44,  28,  -2,  -2, -50,  18,  44,  44,
       -30,  26,  40, -36,  38,   8,   8,   6,  46, -50,  36, -18,  44,
       -12, -40, -28,  38])

In [70]:
# wskaz mediane z zad 5
# zaloz filtr ktory przepusci tylko jednocyfrowe

In [71]:
np.median(tablica)

2.0

In [72]:
tablica[(tablica < 10 ) & (tablica > -10)]

array([-2, -2,  8,  8,  6])

In [73]:
# dla tablic z zad 5 wskaz pozycje elementu kturego sima cyfr jest najwieksza
sumy = list()

for i in list(tablica):
    liczba = [x for x in str(i)]
    if '-' in liczba:
        liczba.remove('-')
    suma = 0
    for l in liczba:
        suma = suma + int(l)
    sumy.append(suma)
    
print(list(tablica))
print(list(sumy))

max_value = max(sumy)
max_index = sumy.index(max_value)
print(sumy[max_index], 'index: ',max_index)



[48, -34, -28, -48, -40, -44, 28, -2, -2, -50, 18, 44, 44, -30, 26, 40, -36, 38, 8, 8, 6, 46, -50, 36, -18, 44, -12, -40, -28, 38]
[12, 7, 10, 12, 4, 8, 10, 2, 2, 5, 9, 8, 8, 3, 8, 4, 9, 11, 8, 8, 6, 10, 5, 9, 9, 8, 3, 4, 10, 11]
12 index:  0


In [75]:
# zad 9 - stworz tablice (NxN) z samymi zerami i wstaw do nie losowe 30% zaokraglone
# reshape change the shape of the table

tablica = np.zeros((10, 10))
shape = tablica.shape[0] * tablica.shape[1]

r = int(round(shape * 0.3, 0))
print(tablica)

tablica = tablica.reshape(-1) # 2d to 1D

i = []
while r > 0:
    index = random.randrange(0,shape)
    if index not in i:
        tablica[index] = 1
        i.append(index)
        r = r -1
        
tablica = tablica.reshape(10,10)
print(tablica)
unique, counts = np.unique(tablica, return_counts=True)
print('unique, counts: ',unique, counts)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0. 1.]]
unique, counts:  [0. 1.] [70 30]


In [77]:
tablica = tablica.reshape(-1)
tablica = tablica.reshape(10,10)

In [78]:
tablica

array([[1., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 1., 0., 1.]])